# FILE LOCATION IN REPOSITORY:
#
#   .github/workflows/checkupdate.yml
#

name: Regular base image update check
on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: set up manifest-tool 
        run: sudo apt-get install -y skopeo
      - name: check change
        run: skopeo inspect docker://registry.access.redhat.com/ubi8/openjdk-11:latest |grep Digest > .baseimage
      - name: do change if the digest changed
        run: |    
          git config user.name 'Update-a-Bot'
          git config user.email 'notifications-team@redhat.com'
          git add -A
          git commit -m "Base image digest changed" || echo "No changes to commit"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
       
